name: Run Tests on Every Commit

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Java 23
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'  # OpenJDK distribution
          java-version: '23'  # Use Java 23

      - name: Verify Java Version
        run: java -version  # Print Java version to verify it's correct

      - name: Set Up Cache for Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            maven-

      - name: Run Tests
        run: mvn test
